name: build-caddy

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  CADDY_VERSION: 2.11.4

jobs:
  build:
    uses: FloatingMilkshake/actions/.forgejo/workflows/docker/docker-build-push.yml@main
    with:
      image-name: floatingmilkshake/caddy-porkbun
      push: ${{ forgejo.event_name == 'workflow_dispatch' || (forgejo.event_name == 'push' && forgejo.ref == 'refs/heads/main') }}
      build-args: CADDY_VERSION=${{ env.CADDY_VERSION }}
      extra-tag: ${{ env.CADDY_VERSION }}
    secrets:
      registry-token: ${{ secrets.REGISTRY_TOKEN }}
